### ISSUE TITLE
Can you provide datasets or weights ?

### ISSUE THREAD

**Issue by RIKOYUKI** [vijuSR/facial_emotion_recognition__EMOJIFIER#17]

**Comment by vijuSR** [comment]
@RIKOYUKI have a look at the [readme file](https://github.com/vijuSR/facial_emotion_recognition__EMOJIFIER/blob/master/README.md). It's super easy to create your dataset. I did it the same way.

**Comment by vijuSR** [comment]
@RIKOYUKI I am closing this issue, feel free to ask if you have any other questions.
